spring.application.name=Backend
spring.datasource.url=jdbc:mysql://root:kpMVQBvvVhnMamQUtBEoXsyfoarHupBf@shortline.proxy.rlwy.net:27963/railway
spring.datasource.username=root
spring.datasource.password=kpMVQBvvVhnMamQUtBEoXsyfoarHupBf
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

cloudinary.cloud-name=dytxsxpue
cloudinary.api-key=313519715645353
cloudinary.api-secret=P6cYNbsGbTADo0zwheQX3iNGN2s

server.tomcat.max-part-count=50

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=${PORT:8080}


mysqldump.path=E:/MySql/bin/mysqldump.exe

